# Generated by Django 5.2.4 on 2025-08-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="profile",
            table="profiles_profile",
        ),
    ]
