version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.11
#commentaire inutile pour rafraichir le dépot au niveau de read the doc
#autre commentaire vain pour rafraichir dépot

  install:
    - requirements: docs/requirements.txt

#autre commentaire pour forcer le push