version: '3.8'

services:
  web:
    image: oc_lettings_local:latest  # Nom fixe de l'image
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=oc_lettings_site.settings
