# Generated by Django 5.2.4 on 2025-08-26 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "managed": False,
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
            },
        ),
        migrations.AlterModelOptions(
            name="letting",
            options={"managed": False},
        ),
    ]
