name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Ou la branche que tu veux surveiller

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # adapte à ta version Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

    - name: Build Docker image
      run: |
        docker build -t andre-sur/ton-image:${{ github.sha }} .

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker push andre-sur/ton-image:${{ github.sha }}

    - name: Deploy to Render (optional)
      uses: render-examples/render-deploy@v1
      with:
        apiKey: ${{ secrets.RENDER_API_KEY }}
        serviceId: ton-service-id

