name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # ou master selon ton projet

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # adapte si nécessaire

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        make install

    - name: Run Lint, Tests, Coverage, Build and Push
      run: |
        make ci

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image (optional if not already done)
      run: |
        docker push $(DOCKER_USER)/$(REPO_NAME):${{ github.sha }}

    - name: Deploy to Render (optional)
      uses: render-examples/render-deploy@v1
      with:
        apiKey: ${{ secrets.RENDER_API_KEY }}
        serviceId: ton-service-id
