# .readthedocs.yaml
version: 2

sphinx:
  configuration: docs/conf.py  # chemin vers ton conf.py

python:
  version: 3.11
  install:
    - requirements: docs/requirements.txt  # si tu as des dépendances
